# Generated by Django 3.0.10 on 2020-09-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200908_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Class')),
            ],
        ),
    ]
