# Generated by Django 3.0.10 on 2020-09-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='class_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Class'),
        ),
    ]
