# Generated by Django 3.0.10 on 2020-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200909_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='question',
            field=models.FileField(blank=True, upload_to='assignment/questions/'),
        ),
    ]
