# Generated by Django 3.0.10 on 2020-09-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_solutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='Student',
            new_name='student',
        ),
    ]
